apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
namespace: pets
commonAnnotations:
  backstage.io/kubernetes-id: <backstage-component> #Dynamic value passed through by template.
